### PR TITLE
Joint Limit Interface

### PR DESCRIPTION
**Pull request by patricknaughton01**
Inside of the TRINA repo it looks like joint limits are set only for the active dofs. However, within the Klampt IK code, it was treating the limits as if they applied to the whole robot configuration. This adjusts the Klampt IK checking to conform to the interface that was used in TRINA.

### CODE REVIEW

**Comment by krishauser** [comment]
This change has potential effects on dozens of functions used outside of your one use case. Have you evaluated its implications thoroughly?

**Comment by patricknaughton01** [comment]
I did not, I only tested it with the use case in _cartesian_drive in the motion module. Instead of changing the Klampt code I can write a small helper to pack in the unset limits with their default values?

**Comment by krishauser** [comment]
I’m open to having different conventions, but their rationale should be clear — and changes should be tested widely and/or made tolerant to old conventions. If this makes sense, we should make an intermediate version that accepts the old version but raises a deprecation warning.

**Comment by patricknaughton01** [comment]
That makes sense. My rationale was that if the solver can only modify the active DoFs, then the user only really needs to worry about setting joint limits on those dofs (since the other ones should be valid already and if they aren't the IK solve shouldn't modify them anyway). It could be made tolerant to the old convention by checking if the limits are the same size as the number of links or number of active dofs and using that to change which index in the limits gets picked for `usedQmin` (and `usedQmax`).

Sticking with the current interface would only necessitate one function I think to pack in the limits for the passed active dofs, so it's not too complicated, but it might be unnecessary. What do you think overall?

**Pull request closed without merging**
