### PR TITLE
Temporarily cap the numpy version

### PR DESCRIPTION
**Pull request by smeng9**
Screenshot 2024-06-17 at 9 55 47 AM

We need to figure out some way to support numpy2 in the future.

### CODE REVIEW

**Comment by krishauser** [comment]
This is now fixed in 0.9.2

**Comment by smeng9** [comment]
Seems the klampt package for Mac is not released yet, Mac install with numpy2 is still broken

**Comment by krishauser** [comment]
Ah, yes. The GitHub action to build this stalled. I’ll see if I can restart it.KrisSent from my iPhoneOn Aug 15, 2024, at 3:11 PM, smeng9 ***@***.***> wrote:﻿
Seems the klampt package for Mac is not released yet, Mac install with numpy2 is still broken

**Comment by krishauser** [comment]
Should be available now.

**Pull request merged**
