### PR TITLE
Installation bug fix, povray integration, pytorch interface.

### PR DESCRIPTION
**Pull request by pzr1988**
Bug fix:
1. syntax bug fix in setup.py.in
2. dependency bug fix in cpp

Klampt to povray:
1. added a copy of vapory library slightly modified by me. (Dependency makefile updated accordingly)
2. klampt to povray main code in Python/klampt/io

pytorch-autodiff, first version, two-way conversion.

### CODE REVIEW

**Comment by krishauser** [comment]
Hi Zherong, the standard mode of using external python modules (PyQt, ROS, etc) is not to include them into Klampt source, but rather to print instructions for installing (I.e. pip install X) and raise an ImportError. Could you please modify this PR accordingly?

**Comment by pzr1988** [comment]
Hi Kris, "vapory" is flawed and does not support latest povray. So I modified the source code, how do you suggest we handle this case? I can add a patch file, and include a series of commands in makefile, first download then apply patch. I feel this is overkill as the library itself is quite small.

**Comment by krishauser** [comment]
Perhaps you can do a monkey-patch for the flawed code upon import? Or is the change more substantial?

**Comment by pzr1988** [comment]
Sure. I will use a patch file.

**Comment by pzr1988** [comment]
Problem fixed.

**Pull request merged**
